import type { Product } from "../types/product";
const image=(id:string)=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&q=85`;
export const fallbackProducts:Product[]=[
{id:"demo-chaunsa",name:"Chaunsa Mango",slug:"chaunsa-mango",sku:"FR-CHAUNSA",description:"Sweet, fragrant Pakistani Chaunsa mangoes, carefully selected for ripeness and quality.",shortDescription:"Premium Pakistani mangoes, naturally sweet and fragrant.",category:"Seasonal Fruits",images:[image("photo-1553279768-865429fa0078")],price:450,compareAtPrice:500,unit:"KG",minQuantity:1,maxQuantity:10,quantityIncrement:.5,stock:40,lowStockThreshold:8,available:true,featured:true,freshPick:true,popular:true,seasonal:true,origin:"Pakistan",grade:"Premium",keywords:["mango","chaunsa"]},
{id:"demo-apple",name:"Red Apple",slug:"red-apple",sku:"FR-APPLE",description:"Crisp red apples selected for balanced sweetness and a clean, juicy bite.",shortDescription:"Crisp, juicy apples for snacks and lunch boxes.",category:"Local Fruits",images:[image("photo-1568702846914-96b305d2aaeb")],price:520,unit:"KG",minQuantity:1,maxQuantity:10,quantityIncrement:1,stock:35,lowStockThreshold:8,available:true,featured:true,freshPick:false,popular:true,seasonal:false,origin:"Pakistan",grade:"Premium",keywords:["apple"]},
{id:"demo-banana",name:"Banana",slug:"banana",sku:"FR-BANANA",description:"Fresh everyday bananas with an even ripeness, ideal for breakfast and smoothies.",shortDescription:"Naturally energising everyday fruit.",category:"Local Fruits",images:[image("photo-1603833665858-e61d17a86224")],price:220,unit:"Dozen",minQuantity:1,maxQuantity:5,quantityIncrement:1,stock:30,lowStockThreshold:6,available:true,featured:true,freshPick:true,popular:true,seasonal:false,origin:"Pakistan",grade:"A",keywords:["banana"]},
{id:"demo-kinnow",name:"Kinnow",slug:"kinnow",sku:"FR-KINNOW",description:"Juicy Pakistani kinnow with a bright citrus flavour, selected for freshness.",shortDescription:"Bright, juicy Pakistani citrus.",category:"Citrus",images:[image("photo-1611080626919-7cf5a9dbab5b")],price:280,unit:"KG",minQuantity:1,maxQuantity:10,quantityIncrement:1,stock:32,lowStockThreshold:8,available:true,featured:true,freshPick:true,popular:true,seasonal:true,origin:"Punjab, Pakistan",grade:"Premium",keywords:["orange","citrus"]}];
export const fallbackCategories=[{id:"seasonal",_id:"seasonal",name:"Seasonal Fruits",value:"seasonal-fruits",image:image("photo-1553279768-865429fa0078"),active:true},{id:"citrus",_id:"citrus",name:"Citrus",value:"citrus",image:image("photo-1611080626919-7cf5a9dbab5b"),active:true},{id:"local",_id:"local",name:"Local Fruits",value:"local-fruits",image:image("photo-1573246123716-6b1782bfc499"),active:true},{id:"boxes",_id:"boxes",name:"Fruit Boxes",value:"fruit-boxes",image:image("photo-1610832958506-aa56368176cf"),active:true}];
export const fallbackAreas=["Johar Town","DHA","Gulberg","Model Town","Bahria Town"].map((name,i)=>({id:`demo-area-${i}`,name,deliveryFee:[150,200,180,150,250][i],minimumOrder:800,freeDeliveryThreshold:4000,active:true}));
export const fallbackSlots=["9 AM – 12 PM","12 PM – 3 PM","3 PM – 6 PM","6 PM – 9 PM"].map((name,i)=>({id:`demo-slot-${i}`,name,days:[0,1,2,3,4,5,6],maxOrders:30,active:true}));
export const fallbackStoreConfig={areas:fallbackAreas,slots:fallbackSlots,categories:fallbackCategories,settings:{codEnabled:false,bankRaastEnabled:false,codMaxAmount:0,deliveryDaysAhead:7,databaseAvailable:false}};
