"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import AdminLayout from "../../components/AdminLayout";
import { money } from "../../lib/domain";

const options = [["all", "All orders"], ["verification_pending", "Needs payment verification"], ["paid", "Paid"], ["cod", "COD"], ["unpaid", "Unpaid"], ["rejected", "Rejected"], ["packing", "Packing"], ["out_for_delivery", "Out for delivery"], ["delivered", "Delivered"], ["cancelled", "Cancelled"]];
export default function Orders() {
  const [orders, setOrders] = useState<any[]>([]), [search, setSearch] = useState(""), [status, setStatus] = useState("all");
  useEffect(() => { const requested = new URLSearchParams(window.location.search).get("status"); if (requested) setStatus(requested); }, []);
  useEffect(() => { const query = new URLSearchParams({ search, status }); fetch(`/api/admin/orders?${query}`).then(r => r.json()).then(data => setOrders(Array.isArray(data) ? data : [])); }, [search, status]);
  return <AdminLayout><h1 className="display text-4xl font-bold">Orders</h1><div className="mt-6 grid gap-3 rounded-2xl bg-white p-4 sm:grid-cols-[1fr_260px]"><input className="field" placeholder="Order, customer or phone" value={search} onChange={e => setSearch(e.target.value)}/><select className="field" value={status} onChange={e => setStatus(e.target.value)}>{options.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></div><div className="card mt-5 overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-[#edf4e9]"><tr>{["Order #", "Customer", "Phone", "Area", "Total", "Payment", "Payment status", "Order status", "Delivery", "Slot", "Action"].map(x => <th className="p-4" key={x}>{x}</th>)}</tr></thead><tbody>{orders.map(order => <tr className={`border-t ${order.paymentStatus === "verification_pending" ? "bg-amber-50" : ""}`} key={order.id}><td className="p-4 font-bold">{order.orderNumber}</td><td className="p-4">{order.customerName}</td><td className="p-4">{order.phone}</td><td className="p-4">{order.address.area}</td><td className="p-4 font-bold">{money(order.total)}</td><td className="p-4">{order.paymentMethod === "cod" ? "COD" : "Bank / Raast"}</td><td className="p-4 capitalize">{order.paymentStatus.replaceAll("_", " ")}</td><td className="p-4 capitalize">{order.orderStatus.replaceAll("_", " ")}</td><td className="p-4">{order.deliveryDate}</td><td className="p-4">{order.deliverySlot}</td><td className="p-4"><Link href={`/admin/orders/${order.id}`} className="font-bold text-[#176b3a]">{order.paymentStatus === "verification_pending" ? "Review Payment →" : "Manage →"}</Link></td></tr>)}</tbody></table>{!orders.length && <p className="p-12 text-center text-[#68766d]">No orders found.</p>}</div></AdminLayout>;
}
