"use client";
import Image from "next/image";
import { useEffect, useState } from "react";
import AdminLayout from "../../../components/AdminLayout";

const defaults = { codEnabled: true, bankRaastEnabled: false, codMaxAmount: 15000, accountTitle: "", bankName: "", accountNumber: "", iban: "", raastId: "", raastQrUrl: "", instructions: "Use your order number as the payment reference." };
export default function PaymentSettings() {
  const [form, setForm] = useState(defaults), [message, setMessage] = useState(""), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  useEffect(() => { fetch("/api/admin/payment-settings").then(r => r.json()).then(data => setForm({ ...defaults, ...data })).catch(() => setError("Could not load payment settings.")); }, []);
  const save = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(""); setMessage(""); const response = await fetch("/api/admin/payment-settings", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(form) }); const data = await response.json(); setBusy(false); if (response.ok) setMessage("Payment settings saved."); else setError(data.error || "Could not save settings."); };
  const upload = async (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; setBusy(true); setError(""); const body = new FormData(); body.set("file", file); const response = await fetch("/api/admin/payment-settings/qr", { method: "POST", body }); const data = await response.json(); setBusy(false); if (response.ok) setForm(current => ({ ...current, raastQrUrl: data.url })); else setError(data.error || "Upload failed."); };
  const field = (key: keyof typeof defaults, label: string) => <label><span className="label">{label}</span><input className="field" value={String(form[key])} onChange={e => setForm({ ...form, [key]: e.target.value })}/></label>;
  return <AdminLayout><div><h1 className="display text-4xl font-bold">Payment settings</h1><p className="mt-2 text-[#68766d]">Control checkout methods and merchant Bank / Raast details.</p></div><form onSubmit={save} className="mt-7 grid max-w-4xl gap-6"><section className="card grid gap-3 p-6 sm:grid-cols-2"><h2 className="text-xl font-extrabold sm:col-span-2">Payment methods</h2><label className="flex items-center gap-3 rounded-xl border p-4"><input type="checkbox" className="h-5 w-5" checked={form.codEnabled} onChange={e => setForm({ ...form, codEnabled: e.target.checked })}/><span><b>Cash on Delivery</b><small className="block text-[#68766d]">Confirm orders immediately.</small></span></label><label className="flex items-center gap-3 rounded-xl border p-4"><input type="checkbox" className="h-5 w-5" checked={form.bankRaastEnabled} onChange={e => setForm({ ...form, bankRaastEnabled: e.target.checked })}/><span><b>Bank / Raast Transfer</b><small className="block text-[#68766d]">Require manual admin verification.</small></span></label><label><span className="label">COD maximum (0 = no limit)</span><input className="field" type="number" min="0" value={form.codMaxAmount} onChange={e => setForm({ ...form, codMaxAmount: Number(e.target.value) })}/></label></section><section className="card grid gap-4 p-6 sm:grid-cols-2"><h2 className="text-xl font-extrabold sm:col-span-2">Merchant bank details</h2>{field("accountTitle", "Account title")}{field("bankName", "Bank name")}{field("accountNumber", "Account number")}{field("iban", "IBAN")}{field("raastId", "Raast ID")}<label className="sm:col-span-2"><span className="label">Customer instructions</span><textarea className="field min-h-28" value={form.instructions} onChange={e => setForm({ ...form, instructions: e.target.value })}/></label><label className="sm:col-span-2"><span className="label">Official Raast QR (JPG, PNG or WEBP, max 5 MB)</span><input className="field" type="file" accept="image/jpeg,image/png,image/webp" onChange={upload}/></label>{form.raastQrUrl && <div className="relative h-56 w-56 overflow-hidden rounded-2xl border bg-white p-3"><Image src={form.raastQrUrl} alt="Configured Raast QR" fill className="object-contain p-3" sizes="224px"/></div>}</section>{error && <p role="alert" className="rounded-xl bg-red-50 p-4 font-bold text-red-700">{error}</p>}{message && <p className="rounded-xl bg-green-50 p-4 font-bold text-green-700">{message}</p>}<button disabled={busy} className="btn btn-primary w-full sm:w-fit">{busy ? "Saving…" : "Save payment settings"}</button></form></AdminLayout>;
}
