"use client";
import { useEffect, useState } from "react";
import AdminLayout from "../../components/AdminLayout";
import { money, slugify } from "../../lib/domain";

const blank: any = { name:"", slug:"", sku:"", description:"", shortDescription:"", category:"Local Fruits", images:[], price:0, compareAtPrice:"", unit:"KG", minQuantity:1, maxQuantity:20, quantityIncrement:1, stock:0, lowStockThreshold:8, available:true, featured:false, freshPick:false, popular:false, seasonal:false, origin:"Pakistan", grade:"Premium", keywords:"" };
const numeric = ["price","compareAtPrice","stock","minQuantity","maxQuantity","quantityIncrement","lowStockThreshold"];

export default function ProductsManager() {
  const [products,setProducts]=useState<any[]>([]); const [categories,setCategories]=useState<any[]>([]);
  const [form,setForm]=useState<any>(blank); const [editing,setEditing]=useState<any>(); const [open,setOpen]=useState(false); const [search,setSearch]=useState("");
  const load=()=>fetch(`/api/admin/products?limit=100&search=${encodeURIComponent(search)}`).then(r=>r.json()).then(d=>setProducts(d.products||[]));
  useEffect(()=>{load()},[search]); useEffect(()=>{fetch("/api/admin/categories").then(r=>r.json()).then(d=>setCategories(Array.isArray(d)?d:[]))},[]);
  const set=(key:string,value:any)=>setForm((f:any)=>({...f,[key]:value}));
  const save=async(e:React.FormEvent)=>{e.preventDefault();const body={...form,image:form.images[0]||"",keywords:String(form.keywords||"").split(",").map(x=>x.trim()).filter(Boolean),compareAtPrice:form.compareAtPrice||null,...(editing?{_id:editing._id}:{})};const r=await fetch("/api/admin/products",{method:editing?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});if(r.ok){setOpen(false);setEditing(undefined);setForm(blank);load()}else alert("Product could not be saved.")};
  const edit=(p:any)=>{setEditing(p);setForm({...blank,...p,compareAtPrice:p.compareAtPrice??"",shortDescription:p.shortDescription??"",description:p.description??"",origin:p.origin??"",grade:p.grade??"",category:p.category??blank.category,unit:p.unit??blank.unit,images:Array.isArray(p.images)&&p.images.length?p.images.filter(Boolean):p.image?[p.image]:[],keywords:Array.isArray(p.keywords)?p.keywords.join(", "):String(p.keywords??"")});setOpen(true)};
  const archive=async(p:any)=>{if(p.archived){const r=await fetch("/api/admin/products",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({...p,_id:p._id,archived:false,available:true})});if(!r.ok)alert("Product could not be restored.");load();return}if(!confirm("Archive this product?"))return;const r=await fetch("/api/admin/products",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({ids:[p._id]})});if(!r.ok)alert("Product could not be archived.");load()};
  return <AdminLayout>
    <div className="flex items-end justify-between gap-3"><div><h1 className="display text-4xl font-bold">Products</h1><p className="text-[#68766d]">Manage active and archived inventory, stock and homepage placement.</p></div><button className="btn btn-primary" onClick={()=>{setEditing(undefined);setForm(blank);setOpen(true)}}>Add product</button></div>
    <input className="field mt-6 max-w-xl" placeholder="Search inventory…" value={search} onChange={e=>setSearch(e.target.value)}/>
    <div className="card mt-5 overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-[#edf4e9]"><tr>{["Product","Category","Price","Unit","Stock","Placement","Actions"].map(x=><th className="p-4" key={x}>{x}</th>)}</tr></thead><tbody>{products.map(p=><tr className={`border-t ${p.archived?"bg-stone-50 text-stone-500":""}`} key={p._id}><td className="p-4"><b>{p.name}</b>{p.archived&&<span className="ml-2 rounded-full bg-stone-200 px-2 py-1 text-[10px] font-black uppercase">Archived</span>}<small className="block text-[#68766d]">{p.sku||p.slug}</small></td><td className="p-4">{p.category}</td><td className="p-4 font-bold">{money(p.price)}</td><td className="p-4">{p.unit||"KG"}</td><td className={p.stock<=(p.lowStockThreshold||8)?"p-4 font-bold text-red-600":"p-4 font-bold"}>{p.stock??"—"}</td><td className="p-4">{[p.featured&&"Featured",p.freshPick&&"Fresh",p.seasonal&&"Seasonal"].filter(Boolean).join(", ")||"—"}</td><td className="p-4"><button onClick={()=>edit(p)} className="font-bold text-[#176b3a]">Edit</button><button onClick={()=>archive(p)} className={`ml-4 font-bold ${p.archived?"text-[#176b3a]":"text-red-600"}`}>{p.archived?"Unarchive":"Archive"}</button></td></tr>)}</tbody></table></div>
    {open&&<div className="fixed inset-0 z-[70] overflow-y-auto bg-black/50 p-3 sm:p-8"><form onSubmit={save} className="card mx-auto max-w-4xl p-6"><div className="flex justify-between"><h2 className="text-2xl font-extrabold">{editing?"Edit":"Add"} product</h2><button type="button" onClick={()=>setOpen(false)}>✕</button></div>
      <div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {[['name','Product name'],['slug','Slug'],['sku','SKU'],['price','Price'],['compareAtPrice','Old price'],['stock','Stock'],['minQuantity','Minimum quantity'],['maxQuantity','Maximum quantity'],['quantityIncrement','Quantity increment'],['lowStockThreshold','Low-stock warning'],['origin','Origin'],['grade','Grade']].map(([key,label])=><label key={key}><span className="label">{label}</span><input required={["name","slug","sku","price"].includes(key)} className="field" type={numeric.includes(key)?"number":"text"} step={numeric.includes(key)?"0.01":undefined} value={form[key]??""} onChange={e=>{const value=numeric.includes(key)?(e.target.value===""?"":Number(e.target.value)):e.target.value;set(key,value);if(key==="name"&&!editing){setForm((f:any)=>({...f,name:value,slug:slugify(String(value)),sku:`FR-${slugify(String(value)).toUpperCase()}`}))}}}/></label>)}
        <label><span className="label">Category</span><select className="field" value={form.category} onChange={e=>set("category",e.target.value)}>{categories.map(c=><option key={c._id}>{c.name}</option>)}</select></label>
        <label><span className="label">Unit</span><select className="field" value={form.unit} onChange={e=>set("unit",e.target.value)}>{["KG","500g","250g","Piece","Dozen","Box","Pack","Basket"].map(x=><option key={x}>{x}</option>)}</select></label>
        <label className="lg:col-span-3"><span className="label">Image URLs (one per line)</span><textarea className="field min-h-20" value={form.images.join("\n")} onChange={e=>set("images",e.target.value.split("\n").filter(Boolean))}/><small>Cloudinary URLs recommended; maximum 5 images, 5 MB upload limit in your Cloudinary preset.</small></label>
        <label className="lg:col-span-3"><span className="label">Short description</span><input className="field" value={form.shortDescription??""} onChange={e=>set("shortDescription",e.target.value)}/></label>
        <label className="lg:col-span-3"><span className="label">Description</span><textarea className="field min-h-28" value={form.description??""} onChange={e=>set("description",e.target.value)}/></label>
        <label className="lg:col-span-3"><span className="label">Search keywords, comma separated</span><input className="field" value={form.keywords??""} onChange={e=>set("keywords",e.target.value)}/></label>
      </div>
      <div className="mt-5 grid gap-3 sm:grid-cols-3">{[["available","Available"],["featured","Featured"],["freshPick","Fresh pick"],["popular","Popular"],["seasonal","Seasonal"]].map(([key,label])=><label className="flex gap-2 rounded-xl border p-3" key={key}><input type="checkbox" checked={Boolean(form[key])} onChange={e=>set(key,e.target.checked)}/><b>{label}</b></label>)}</div>
      <button className="btn btn-primary mt-6 w-full">Save product</button>
    </form></div>}
  </AdminLayout>;
}
